"""Presentation metadata, separate from the workbook's protocol and legacy IDs.

Addresses below refer to the selected protocol sheet, not Modbus offsets. Keep
the workbook names intact: existing ESPHome IDs and native API keys use them.
"""

# These settings have the same meaning in both protocol sheets.
COMMON_NAMES = {
    1011: "Power",
    1012: "Operating mode",
    1014: "Electric heater independent operation",
    1015: "Defrost forced operation",
    1016: "Ventilation mode",
    1020: "Output O05 function",
    1021: "Output O06 function",
    1034: "Defrost start temperature",
    1035: "Defrost stop temperature",
    1036: "Defrost interval",
    1037: "Defrost maximum duration",
    1038: "Defrost minimum duration",
    1039: "Defrost mode",
    1040: "Defrost smart mode temperature threshold",
    1046: "Disinfection target temperature",
    1047: "Disinfection hold time",
    1048: "Disinfection start hour",
    1049: "Disinfection interval",
    1055: "Expansion valve control mode",
    1056: "Expansion valve target superheat",
    1057: "Expansion valve initial position",
    1058: "Expansion valve minimum position",
    1059: "Expansion valve defrost position",
    1067: "Restore state after power loss",
    1069: "Heat source type",
    1073: "Display temperature unit",
    1074: "Control panel model code",
    1075: "Display temperature compensation",
    1080: "Solar pump control sensor",
    1081: "Solar pump maximum run time",
    1082: "Solar pump start temperature difference",
    1083: "Night cooling enabled",
    1084: "Night cooling start hour",
    1085: "Night cooling stop hour",
    1086: "Night cooling start temperature",
    1087: "Night cooling stop temperature difference",
    1088: "Solar drain valve temperature threshold",
    1089: "Solar pump stop temperature",
    1090: "Solar pump independent operation",
    1104: "Water target temperature",
    1106: "Tank lower reheat differential",
    1107: "Electric heater separate target enabled",
    1108: "Electric heater target temperature",
    1109: "Electric heater start delay",
    1110: "Electric heater takeover enabled",
    1111: "Electric heater takeover ambient temperature",
    1112: "Electric heater immediate start ambient temperature",
    1113: "Electric heater delayed start ambient temperature",
    1115: "Compressor low ambient cutoff",
    1117: "Auxiliary heat source target temperature",
    # The English sheet calls these ambient limits; the Chinese sheet does not.
    # Do not invent which temperature sensor supplies the high-temperature limit.
    1118: "Compressor high temperature cutoff",
    1120: "Tank upper sensor control enabled",
    1121: "Tank upper reheat differential",
    1122: "Compressor high temperature cutoff 1",
    1123: "Compressor high temperature cutoff 2",
    1129: "Vacation date enabled",
    1130: "Vacation year",
    1131: "Vacation month",
    1132: "Vacation day",
    1133: "Timer enable flags",
    1134: "Timer 1 start hour",
    1135: "Timer 1 start minute",
    1136: "Timer 1 stop hour",
    1137: "Timer 1 stop minute",
    1138: "Timer 2 start hour",
    1139: "Timer 2 start minute",
    1140: "Timer 2 stop hour",
    1141: "Timer 2 stop minute",
}

# Telemetry and clock addresses differ between the two sheets.
REGISTER_NAMES = {
    "dtu_wifi": {
        **COMMON_NAMES,
        1013: "Operating mode active",
        1066: "Cloud reporting interval",
        1076: "Modbus address",
        1077: "Control interface",
        1151: "Clock update flag",
        1152: "Clock minute setting",
        1153: "Clock hour setting",
        1154: "Clock day setting",
        1155: "Clock month setting",
        1156: "Clock year setting",
        1158: "Network module heartbeat",
        2011: "Main controller firmware version",
        2012: "Main controller firmware code",
        2013: "Control panel firmware version",
        2014: "Control panel firmware code",
        2019: "Ambient temperature",
        2020: "Tank temperature lower",
        2021: "Tank temperature upper",
        2022: "Coil temperature",
        2023: "Refrigerant suction temperature",
        2024: "Solar sensor temperature",
        2025: "Water temperature",
        2026: "Parameter out of range count",
        2027: "EEPROM write count",
        2050: "Component status flags",
        2051: "Operating status flags",
        2060: "Expansion valve position",
        2061: "Compressor run time",
        2062: "Electric heater run time",
        2085: "Fault flags",
    },
    "hw211": {
        **COMMON_NAMES,
        1025: "Ambient compensation enabled",
        1026: "Ambient compensation maximum offset",
        1027: "Ambient compensation coefficient",
        1028: "Ambient compensation start temperature",
        1060: "Expansion valve low ambient threshold",
        1061: "Expansion valve low ambient position",
        1068: "Cooling mode enabled",
        1070: "Source pump compressor lead time",
        1071: "Cooling independent operation enabled",
        1072: "Cooling independent operation duration",
        1105: "Cooling target temperature",
        1114: "Circulation pump on time",
        1116: "Cooling mode changeover temperature",
        1119: "Fan speed changeover ambient temperature",
        1149: "Manual output flags",
        1150: "Clock update flag",
        1151: "Clock hour setting",
        1152: "Clock minute setting",
        1153: "Clock month setting",
        1154: "Clock day setting",
        1155: "Clock weekday setting",
        1156: "Clock year setting",
        1157: "Modbus address",
        1158: "Control interface",
        2011: "Ambient temperature",
        2012: "Tank temperature lower",
        2013: "Tank temperature upper",
        2014: "Coil temperature",
        2015: "Refrigerant suction temperature",
        2016: "Solar sensor temperature",
        2019: "Expansion valve position",
        2020: "Compressor run time",
        2021: "Electric heater run time",
        2030: "Component status flags",
        2031: "Operating status flags",
        2060: "Fault flags",
        2077: "Main controller firmware version",
        2078: "Main controller firmware code",
        # This sheet repeats the main-program label for the second pair.
        2079: "Secondary controller firmware version",
        2080: "Secondary controller firmware code",
    },
}

COMMON_BIT_NAMES = {
    1129: {0: "Vacation date enabled"},
    1133: {
        0: "Timer 1 start enabled",
        1: "Timer 1 stop enabled",
        2: "Timer 2 start enabled",
        3: "Timer 2 stop enabled",
    },
}
COMPONENT_BIT_NAMES = {
    0: "Remote switch input open",
    2: "Low pressure switch input open",
    3: "High pressure switch input open",
    4: "Shortened timing input open",
    6: "Component reserved bit 6",
    7: "Component reserved bit 7",
    8: "Compressor running",
    9: "Electric heater running",
    10: "Reversing valve active",
    11: "Fan high speed active",
    # O05/O06 have configurable functions; they are not always fan/solar outputs.
    12: "Output O05 active",
    13: "Output O06 active",
}
FAULT_BIT_NAMES = {
    0: "Fault ambient temperature sensor",
    1: "Fault lower tank temperature sensor",
    2: "Fault upper tank temperature sensor",
    3: "Fault coil temperature sensor",
    4: "Fault suction temperature sensor",
    5: "Fault solar temperature sensor",
    8: "Protection high pressure",
    9: "Protection low pressure",
    13: "Protection tank frost",
}
BIT_NAMES = {
    "dtu_wifi": {
        **COMMON_BIT_NAMES,
        2050: {
            **COMPONENT_BIT_NAMES,
            5: "External heat source input active",
            14: "Electronic anode 3 V output active",
            15: "Electronic anode MV output active",
        },
        2051: {
            0: "Thermostat satisfied",
            1: "Network module online",
            2: "Defrost active",
            3: "Hot water mode active",
        },
        2085: FAULT_BIT_NAMES,
    },
    "hw211": {
        **COMMON_BIT_NAMES,
        1149: {bit: f"Manual output O{bit + 1:02d} active" for bit in range(8)},
        2030: {
            **COMPONENT_BIT_NAMES,
            1: "Electric heater overload input closed",
            5: "Water flow input stopped",
        },
        2031: {
            0: "Thermostat satisfied",
            1: "Network module control selected",
            2: "Defrost active",
        },
        2060: {
            **FAULT_BIT_NAMES,
            10: "Protection electric heater overheat",
            11: "Protection water flow",
            12: "Protection frost",
            14: "Protection second stage frost",
        },
    },
}

# Only everyday operating controls/readings belong in the main HA cards.
# Other read-only entities are diagnostics; writable settings are configuration.
# Keep optional writable controls accessible even when their readbacks are diagnostic.
PRIMARY_CONTROLS = {1011, 1012, 1013, 1014, 1016, 1104, 1105, 1108}
PRIMARY_REGISTERS = {
    "dtu_wifi": {1104, 1105, 2019, 2020, 2021, 2022, 2025},
    "hw211": {1104, 1105, 2011, 2012, 2013, 2014},
}
PRIMARY_BITS = {
    "dtu_wifi": {2050: {8, 9, 10, 11, 12, 13}, 2051: {0, 2, 3}},
    "hw211": {2030: {8, 9, 10, 11, 12, 13}, 2031: {0, 2}},
}

# Correct copied/missing display units only where the existing numeric conversion
# is known. The HW211 sheet lacks scale types, so do not infer new conversions.
UNIT_OVERRIDES = {
    "dtu_wifi": {
        1036: "min",
        1057: "steps",
        1058: "steps",
        1059: "steps",
        1109: "min",
        2060: "steps",
        2061: "h",
        2062: "h",
    },
    "hw211": {2019: "steps", 2020: "h", 2021: "h"},
}
